apiVersion: v1
kind: ConfigMap
metadata:
  name: application-envs
data:
  mysql_root_password: "1234"
  mysql_host: "application-db-service"
  rabbit_url: "amqp://user:1234@message-broker-service:5672/vhost"