apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-mongo-deployment
spec:
  selector:
    matchLabels:
      app: JobTH
      service: job
      db: mongo
  template:
    metadata:
      labels:
        app: JobTH
        service: job
        db: mongo
    spec:
      containers:
      - name: job-mongo
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: job-db-volume
            mountPath: /var/lib
      volumes:
        - name: job-db-volume
          persistentVolumeClaim:
            claimName: job-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: job-mongo-service
spec:
  selector:
    app: JobTH
    service: job
    db: mongo
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP

