apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-statistic-mongo-deployment
spec:
  selector:
    matchLabels:
      app: JobTH
      service: job-statistic
      db: mongo
  template:
    metadata:
      labels:
        app: JobTH
        service: job-statistic
        db: mongo
    spec:
      containers:
        - name: job-statistic-mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: job-statistic-db-volume
              mountPath: /var/lib
      volumes:
        - name: job-statistic-db-volume
          persistentVolumeClaim:
            claimName: job-statistic-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: job-statistic-db-service
spec:
  selector:
    app: JobTH
    service: job-statistic
    db: mongo
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
