apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: JobTH
      service: profile
  template:
    metadata:
      labels:
        app: JobTH
        service: profile
    spec:
      containers:
        - name: profile-service
          image: warathep187/profile-service
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: profile-envs
                  key: mongodb_uri
            - name: RABBIT_URL
              valueFrom:
                configMapKeyRef:
                  name: profile-envs
                  key: rabbit_url
          ports:
            - containerPort: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  selector:
    app: JobTH
    service: profile
  ports:
    - port: 80
      targetPort: 8001
  type: LoadBalancer
