apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: JobTH
      service: application
  template:
    metadata:
      labels:
        app: JobTH
        service: application
    spec:
      containers:
      - name: application-service
        image: warathep187/application-service:v3
        env:
          - name: RABBIT_URL
            valueFrom:
              configMapKeyRef:
                name: application-envs
                key: rabbit_url
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: application-envs
                key: mysql_host
          - name: MYSQL_USER
            value: "root"
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: application-envs
                key: mysql_root_password
        ports:
        - containerPort: 8003
        livenessProbe:
          httpGet:
            path: /api/application
            port: 8003
          initialDelaySeconds: 15
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: application-service
spec:
  selector:
    app: JobTH
    service: application
  ports:
  - port: 80
    targetPort: 8003
  type: LoadBalancer
