apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  selector:
    matchLabels:
      app: JobTH
      service: auth
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: JobTH
        service: auth
    spec:
      containers:
        - name: auth-service
          image: warathep187/auth-service:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: auth-envs
                  key: mysql_url
            - name: RABBIT_URL
              valueFrom:
                configMapKeyRef:
                  name: auth-envs
                  key: rabbit_url
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: auth-envs
                  key: redis_url
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /api/auth
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: JobTH
    service: auth
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer
