apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-broker-deployment
spec:
  selector:
    matchLabels:
      app: JobTH
      service: message-broker
  template:
    metadata:
      labels:
        app: JobTH
        service: message-broker
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                configMapKeyRef:
                  name: broker-envs
                  key: user
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                configMapKeyRef:
                  name: broker-envs
                  key: password
            - name: RABBITMQ_DEFAULT_VHOST
              valueFrom:
                configMapKeyRef:
                  name: broker-envs
                  key: vhost
          ports:
            - containerPort: 5672

---
apiVersion: v1
kind: Service
metadata:
  name: message-broker-service
spec:
  selector:
    app: JobTH
    service: message-broker
  ports:
    - port: 5672
      targetPort: 5672
  type: ClusterIP
