apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: JobTH
      service: job
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: JobTH
        service: job
    spec:
      containers:
      - name: job-service
        image: warathep187/job-service
        env:
          - name: RABBIT_URL
            valueFrom:
              configMapKeyRef:
                name: job-envs
                key: rabbit_url
          - name: MONGODB_URI
            valueFrom:
              configMapKeyRef:
                name: job-envs
                key: mongodb_uri
        ports:
        - containerPort: 8002
        livenessProbe:
          httpGet:
            path: /api/job
            port: 8002

---
apiVersion: v1
kind: Service
metadata:
  name: job-service
spec:
  selector:
    app: JobTH
    service: job
  ports:
  - port: 80
    targetPort: 8002
  type: LoadBalancer
