apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-searching-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: JobTH
      service: job-searching
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: JobTH
        service: job-searching
    spec:
      containers:
      - name: job-searching-service
        image: warathep187/job-searching-service
        env:
          - name: RABBIT_URL
            valueFrom:
              configMapKeyRef:
                name: job-searching-envs
                key: rabbit_url
          - name: ELASTIC_USERNAME
            value: elastic
          - name: ELASTIC_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: job-searching-envs
                key: elasticsearch_password
          - name: ELASTIC_NODE
            valueFrom:
              configMapKeyRef:
                name: job-searching-envs
                key: elasticsearch_node
        ports:
        - containerPort: 8006
        livenessProbe:
          httpGet:
            path: /api/job-searching
            port: 8006

---
apiVersion: v1
kind: Service
metadata:
  name: job-searching-service
spec:
  selector:
    app: JobTH
    service: job-searching
  ports:
  - port: 80
    targetPort: 8006
  type: LoadBalancer
