apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
spec:
  selector:
    matchLabels:
      app: JobTH
      service: notification
  template:
    metadata:
      labels:
        app: JobTH
        service: notification
    spec:
      containers:
      - name: notification-service
        image: warathep187/notification-service:v2
        env:
          - name: REDIS_URL
            valueFrom:
              configMapKeyRef:
                name: notification-envs
                key: redis_url
          - name: MONGODB_URI
            valueFrom:
              configMapKeyRef:
                name: notification-envs
                key: mongodb_uri
          - name: RABBIT_URL
            valueFrom:
              configMapKeyRef:
                name: notification-envs
                key: rabbit_url
        ports:
        - containerPort: 8008
        livenessProbe:
          httpGet:
            path: /api/notification
            port: 8008

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: JobTH
    service: notification
  ports:
  - port: 80
    targetPort: 8008
  type: LoadBalancer
